# Generated by Django 5.1.7 on 2025-03-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='trainee/images/')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.track2')),
            ],
        ),
    ]
