# Generated by Django 4.1 on 2025-03-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(default=22, upload_to='trainee/images'),
            preserve_default=False,
        ),
    ]
