# Generated by Django 4.1 on 2025-03-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
        ('trainee', '0003_trainee_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='track',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='track.track2'),
            preserve_default=False,
        ),
    ]
