# Generated by Django 4.1 on 2025-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0004_trainee_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.ImageField(upload_to='trainee/images/'),
        ),
    ]
